import type { PlannerState } from "./types";

export const initialState: PlannerState = {
  title: "Pacific out, mountain home",
  start: {
    name: "Taipei",
    lat: 25.033,
    lng: 121.5654,
  },
  sources: [
    {
      id: "official-route-one",
      title: "Cycling in Taiwan",
      publisher: "Taiwan Tourism Administration",
      kind: "official",
      url: "https://eng.taiwan.net.tw/m1.aspx?sNo=0029976",
      usedFor:
        "Route 1 baseline, signed cycling infrastructure, and the 20 km rest-station network.",
    },
    {
      id: "east-coast-routes",
      title: "East Coast cycling tours",
      publisher: "East Coast National Scenic Area",
      kind: "official",
      url: "https://www.eastcoast-nsa.gov.tw/en/travel/bike-themes/",
      usedFor:
        "Highway 11 coastal routing and the Shimen–Changbin and Sanxiantai–Chenggong bike paths.",
    },
    {
      id: "east-coast-depots",
      title: "East Coast cyclist service stations",
      publisher: "East Coast National Scenic Area",
      kind: "official",
      url: "https://www.eastcoast-nsa.gov.tw/en/travel/cycling/stations/",
      usedFor:
        "Police-station bike depots, water, charging, basic tools, addresses, and phone numbers.",
    },
    {
      id: "official-camps",
      title: "Legal campground search",
      publisher: "Taiwan Tourism Administration",
      kind: "official",
      url: "https://camp.tad.gov.tw/",
      usedFor:
        "Registration checks for formal campgrounds. Recheck every campground before departure.",
    },
    {
      id: "official-camps-data",
      title: "Campground Information for the Whole of Taiwan",
      publisher: "Taiwan Tourism Administration",
      kind: "official",
      url: "https://data.gov.tw/en/datasets/132066",
      usedFor:
        "Island-wide campground names, coordinates, addresses, websites, and regulatory-compliance labels. Open Government Data License 1.0; updated every March.",
    },
    {
      id: "taipei-free-camps",
      title: "Where to Go City Camping",
      publisher: "Taipei Travel",
      kind: "official",
      url: "https://www.travel.taipei/en/pictorial/article/65940",
      usedFor:
        "Free-camping status and reservation guidance for Bishan and Guizikeng public campgrounds.",
    },
    {
      id: "official-onsens",
      title: "Taiwan hot-spring regions",
      publisher: "Taiwan Tourism Administration",
      kind: "official",
      url: "https://eng.taiwan.net.tw/m1.aspx?sNo=0002008",
      usedFor:
        "Hot-spring regions and the onsen anchors shown throughout the itinerary.",
    },
    {
      id: "shitiping-official",
      title: "Shitiping Campsite",
      publisher: "East Coast National Scenic Area",
      kind: "official",
      url: "https://www.eastcoast-nsa.gov.tw/en/camping-area/3631/",
      usedFor:
        "Current Shitiping contact details and the requirement to register before pitching.",
    },
    {
      id: "walker-east-coast",
      title: "Taiwan 08: Taitung — Shitiping",
      publisher: "Walker Kim",
      kind: "rider report",
      url: "https://blog.walker.kim/2018/04/24/taiwan-08-taitung-shitiping/",
      usedFor:
        "First-hand Highway 11 conditions, Changbin resupply, separated path sections, and a Shitiping camp experience.",
    },
    {
      id: "wild-camp-thread",
      title: "East Coast wild camping",
      publisher: "r/taiwan community",
      kind: "community",
      url: "https://www.reddit.com/r/taiwan/comments/16p8hpm/east_coast_wild_camping/",
      usedFor:
        "Anecdotal east-coast beach camping and the Tiaolang tunnel-area lead. Not legal confirmation.",
    },
    {
      id: "east-coast-camp-thread",
      title: "Taiwan East Coast",
      publisher: "r/bicycletouring community",
      kind: "community",
      url: "https://www.reddit.com/r/bicycletouring/comments/17dizno/taiwan_east_coast/",
      usedFor:
        "A rider report of simple, free camping along the east coast for two weeks.",
    },
    {
      id: "tim-mathis",
      title: "Taiwan Cycle Route 1: what English-speakers need to know",
      publisher: "Tim Mathis",
      kind: "rider report",
      url: "https://www.timmathiswrites.com/post/taiwan-cycle-route-1-english-speakers",
      usedFor:
        "Use Route 1 as a guideline, get off highways when possible, and ask at rural temples or police stations rather than assuming.",
    },
    {
      id: "david-sykes",
      title: "A bicycle tour around Taiwan",
      publisher: "David Sykes",
      kind: "rider report",
      url: "https://davidsykes.substack.com/p/a-bicycle-tour-around-taiwan",
      usedFor:
        "Avoiding the urban west, the Puli–Wuling climb, Sun Moon Lake, Dongpu hot springs, Alishan, and weather-driven rerouting.",
    },
    {
      id: "bike-express-wuling",
      title: "Five extremes around Taiwan: Wuling",
      publisher: "Bike Express Taiwan",
      kind: "rider report",
      url: "https://www.bikeexpress.com.tw/2025/cycle-the-five-extremes-around-taiwan-conquering-wuling-pass/",
      usedFor:
        "The Wuling–Lishan–Yilan line, sparse resupply, and the need to reserve lodging and check mountain roads.",
    },
    {
      id: "road-conditions",
      title: "Provincial highway conditions",
      publisher: "Highway Bureau, MOTC",
      kind: "official",
      url: "https://168.thb.gov.tw/",
      usedFor:
        "Mandatory pre-ride checks for Suhua, Wuling, mountain highways, closures, and traffic controls.",
    },
    {
      id: "brouter",
      title: "BRouter bicycle routing engine",
      publisher: "BRouter",
      kind: "community",
      url: "https://github.com/abrensch/brouter",
      usedFor:
        "Road-by-road bicycle route geometry, distance, and estimated ascent between each editable overnight stop.",
    },
  ],
  days: [
    {
      id: "day-1",
      day: 1,
      from: "Taipei",
      to: "Fulong",
      lat: 25.0165,
      lng: 121.9441,
      distance: 72,
      climbing: 720,
      surface: "Riverside paths · Hwy 2 cycle lanes",
      camp: "Longmen Campground",
      onsen: null,
      note: "Leave the city on riverside paths, then take the quiet northeast coast.",
      difficulty: "steady",
    },
    {
      id: "day-2",
      day: 2,
      from: "Fulong",
      to: "Jiaoxi",
      lat: 24.8278,
      lng: 121.771,
      distance: 61,
      climbing: 540,
      surface: "Old Caoling loop · coastal cycleway",
      camp: "Camping lead near Toucheng",
      onsen: "Jiaoxi public hot spring",
      note: "A deliberately short day for the Caoling tunnel and an evening soak.",
      difficulty: "steady",
    },
    {
      id: "day-3",
      day: 3,
      from: "Jiaoxi",
      to: "Dong'ao",
      lat: 24.5183,
      lng: 121.8307,
      distance: 68,
      climbing: 690,
      surface: "Yilan cycleways · local roads",
      camp: "Dong'ao camping lead",
      onsen: "Su'ao cold spring",
      note: "Use the Yilan river paths and avoid central Luodong where possible.",
      difficulty: "steady",
    },
    {
      id: "day-4",
      day: 4,
      from: "Dong'ao",
      to: "Hualien",
      lat: 23.9911,
      lng: 121.6112,
      distance: 76,
      climbing: 910,
      surface: "Suhua corridor · shared road",
      camp: "Hualien coastal camping lead",
      onsen: null,
      note: "Safety-critical section. Confirm every tunnel and road opening locally.",
      difficulty: "big",
    },
    {
      id: "day-5",
      day: 5,
      from: "Hualien",
      to: "Shitiping",
      lat: 23.4835,
      lng: 121.5084,
      distance: 70,
      climbing: 760,
      surface: "Hwy 11 shoulder · coastal bikeway pieces",
      camp: "Shitiping Campground",
      onsen: null,
      note: "Open Pacific riding with limited resupply after Fengbin.",
      difficulty: "steady",
    },
    {
      id: "day-6",
      day: 6,
      from: "Shitiping",
      to: "Chenggong",
      lat: 23.1003,
      lng: 121.3768,
      distance: 63,
      climbing: 630,
      surface: "Hwy 11 · Shimen/Changbin bike paths",
      camp: "Pisilian Campground",
      onsen: null,
      note: "Use the signed coastal bike-path fragments whenever they appear.",
      difficulty: "steady",
    },
    {
      id: "day-7",
      day: 7,
      from: "Chenggong",
      to: "Dulan",
      lat: 22.873,
      lng: 121.2295,
      distance: 58,
      climbing: 460,
      surface: "Sanxiantai path · Hwy 11 shoulder",
      camp: "Dulan camping lead",
      onsen: null,
      note: "A lighter day with time for Sanxiantai and village food.",
      difficulty: "easy",
    },
    {
      id: "day-8",
      day: 8,
      from: "Dulan",
      to: "Zhiben",
      lat: 22.6934,
      lng: 121.0166,
      distance: 55,
      climbing: 410,
      surface: "Coastal road · Taitung bike paths",
      camp: "Jhihben camping lead",
      onsen: "Zhiben Hot Spring",
      note: "Thread around Taitung on waterfront paths before turning inland.",
      difficulty: "easy",
    },
    {
      id: "day-9",
      day: 9,
      from: "Zhiben",
      to: "Kenting",
      lat: 21.9462,
      lng: 120.7983,
      distance: 104,
      climbing: 1450,
      surface: "Hwy 9 · Route 199/200",
      camp: "Kenting campground",
      onsen: "Sichongxi Hot Spring",
      note: "The Shouka crossing is long and exposed. Split at Dawu if needed.",
      difficulty: "big",
    },
    {
      id: "day-10",
      day: 10,
      from: "Kenting",
      to: "Meinong",
      lat: 22.8993,
      lng: 120.5477,
      distance: 96,
      climbing: 820,
      surface: "Rural Pingtung roads · riverside sections",
      camp: "Meinong camping lead",
      onsen: null,
      note: "Turn inland early to bypass Kaohsiung's urban belt.",
      difficulty: "big",
    },
    {
      id: "day-11",
      day: 11,
      from: "Meinong",
      to: "Guanziling",
      lat: 23.336,
      lng: 120.505,
      distance: 92,
      climbing: 1320,
      surface: "Hwy 3 · rural foothill roads",
      camp: "Ask-first or legal camp near Guanziling",
      onsen: "Guanziling Hot Spring",
      note: "The central return begins. Stay inland through the foothills and bypass Tainan.",
      difficulty: "big",
    },
    {
      id: "day-12",
      day: 12,
      from: "Guanziling",
      to: "Alishan",
      lat: 23.511,
      lng: 120.805,
      distance: 82,
      climbing: 2100,
      surface: "Hwy 3/18 · mountain roads",
      camp: "Book or ask-first near Alishan",
      onsen: null,
      note: "Long high climb. Confirm the exact low-traffic link and road status locally.",
      difficulty: "big",
    },
    {
      id: "day-13",
      day: 13,
      from: "Alishan",
      to: "Dongpu",
      lat: 23.561,
      lng: 120.927,
      distance: 95,
      climbing: 2140,
      surface: "Hwy 18/21 · remote mountain road",
      camp: "Dongpu paid or ask-first backup",
      onsen: "Dongpu Hot Spring",
      note: "Reverse of a rider-tested mountain stage; remote, beautiful, and landslide-prone.",
      difficulty: "big",
    },
    {
      id: "day-14",
      day: 14,
      from: "Dongpu",
      to: "Puli",
      lat: 23.9663,
      lng: 120.969,
      distance: 76,
      climbing: 920,
      surface: "Hwy 21 · Sun Moon Lake bike path",
      camp: "Puli camping lead",
      onsen: null,
      note: "Take the lakeside path, then recover and decide whether the Wuling line is open.",
      difficulty: "steady",
    },
    {
      id: "day-15",
      day: 15,
      from: "Puli",
      to: "Wuling",
      lat: 24.137,
      lng: 121.2758,
      distance: 56,
      climbing: 2850,
      surface: "Hwy 14/14A · alpine road",
      camp: "Book mountain lodging",
      onsen: "Lushan area (verify access)",
      note: "Expert-only alpine variant. No casual camping; book shelter and check weather.",
      difficulty: "big",
    },
    {
      id: "day-16",
      day: 16,
      from: "Wuling",
      to: "Yilan",
      lat: 24.757,
      lng: 121.753,
      distance: 106,
      climbing: 920,
      surface: "Hwy 8/7A · mountain descent",
      camp: "Yilan camping lead",
      onsen: "Jiaoxi Hot Spring",
      note: "Long remote descent. Road openings determine whether this variant is possible.",
      difficulty: "big",
    },
    {
      id: "day-17",
      day: 17,
      from: "Yilan",
      to: "Taipei",
      lat: 25.033,
      lng: 121.5654,
      distance: 64,
      climbing: 1150,
      surface: "Hwy 9 · riverside paths",
      camp: "Finish",
      onsen: null,
      note: "Climb through Pinglin, then re-enter Taipei on the river network.",
      difficulty: "big",
    },
  ],
  places: [
    {
      id: "camp-longmen",
      name: "Longmen Campground",
      kind: "camp",
      lat: 25.021,
      lng: 121.929,
      note: "Established campground near Fulong. Verify bike/tent rate.",
      verified: false,
      sleepStyle: "registered",
      sourceIds: ["official-camps"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Longmen+Camping+Ground+Taiwan",
    },
    {
      id: "camp-shitiping",
      name: "Shitiping Campground",
      kind: "camp",
      lat: 23.485,
      lng: 121.51,
      note: "Useful official east-coast camping stop.",
      verified: true,
      sleepStyle: "registered",
      sourceIds: ["shitiping-official", "walker-east-coast"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Shitiping+Campsite+Taiwan",
    },
    {
      id: "camp-pisilian",
      name: "Pisilian Campground",
      kind: "camp",
      lat: 23.126,
      lng: 121.4,
      note: "Registered campground near Sanxiantai.",
      verified: false,
      sleepStyle: "registered",
      sourceIds: ["official-camps"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Pisilian+Campground+Taiwan",
    },
    {
      id: "camp-xiaoyeliu",
      name: "Xiaoyeliu Campground",
      kind: "camp",
      lat: 22.794,
      lng: 121.198,
      note: "Established coastal campground north of Taitung.",
      verified: false,
      sleepStyle: "registered",
      sourceIds: ["official-camps"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Xiaoyeliu+Campground+Taiwan",
    },
    {
      id: "wild-tiaolang",
      name: "Tiaolang tunnel-area lead",
      kind: "camp",
      lat: 24.242,
      lng: 121.739,
      note: "Community-reported abandoned-road bivy. Approximate pin only: inspect in daylight, avoid tunnels/closures, and move on if access is restricted.",
      verified: false,
      sleepStyle: "wild lead",
      sourceIds: ["wild-camp-thread"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Tiaolang+Old+Trail+Taiwan",
    },
    {
      id: "ask-gangkou",
      name: "Gangkou cyclist depot",
      kind: "camp",
      lat: 23.467,
      lng: 121.496,
      note: "Official water/rest/charging point. Ask in person about any overnight option; it is not promised.",
      verified: true,
      sleepStyle: "ask first",
      sourceIds: ["east-coast-depots", "tim-mathis"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Gangkou+Police+Station+Fengbin+Taiwan",
    },
    {
      id: "ask-dulan",
      name: "Dulan cyclist depot",
      kind: "camp",
      lat: 22.874,
      lng: 121.227,
      note: "Official cyclist rest point. Ask politely before considering a bivy nearby; have a paid fallback.",
      verified: true,
      sleepStyle: "ask first",
      sourceIds: ["east-coast-depots", "tim-mathis"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Dulan+Police+Station+Taitung+Taiwan",
    },
    {
      id: "onsen-jiaoxi",
      name: "Jiaoxi Hot Spring",
      kind: "onsen",
      lat: 24.828,
      lng: 121.771,
      note: "Public footbaths and private baths; a natural early rest stop.",
      verified: true,
      sourceIds: ["official-onsens"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Jiaoxi+Hot+Spring+Taiwan",
    },
    {
      id: "onsen-ruisui",
      name: "Ruisui Hot Spring",
      kind: "onsen",
      lat: 23.496,
      lng: 121.347,
      note: "Carbonate hot spring in the East Rift Valley; optional inland detour.",
      verified: true,
      sourceIds: ["official-onsens"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Ruisui+Hot+Spring+Taiwan",
    },
    {
      id: "onsen-antong",
      name: "Antong Hot Spring",
      kind: "onsen",
      lat: 23.281,
      lng: 121.341,
      note: "A rewarding detour if crossing between coast and rift valley.",
      verified: true,
      sourceIds: ["official-onsens"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Antong+Hot+Spring+Taiwan",
    },
    {
      id: "onsen-zhiben",
      name: "Zhiben Hot Spring",
      kind: "onsen",
      lat: 22.693,
      lng: 121.016,
      note: "Classic Taitung hot-spring area before the southern crossing.",
      verified: true,
      sourceIds: ["official-onsens"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Zhiben+Hot+Spring+Taiwan",
    },
    {
      id: "onsen-sichongxi",
      name: "Sichongxi Hot Spring",
      kind: "onsen",
      lat: 22.096,
      lng: 120.744,
      note: "Historic hot-spring village north of Kenting.",
      verified: true,
      sourceIds: ["official-onsens"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Sichongxi+Hot+Spring+Taiwan",
    },
    {
      id: "onsen-guanziling",
      name: "Guanziling Hot Spring",
      kind: "onsen",
      lat: 23.336,
      lng: 120.505,
      note: "Mud hot spring on the rural central return.",
      verified: true,
      sourceIds: ["official-onsens"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Guanziling+Hot+Spring+Taiwan",
    },
    {
      id: "onsen-dongpu",
      name: "Dongpu Hot Spring",
      kind: "onsen",
      lat: 23.561,
      lng: 120.927,
      note: "Remote mountain hot-spring stop used in David Sykes' central route.",
      verified: true,
      sourceIds: ["david-sykes"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Dongpu+Hot+Spring+Taiwan",
    },
    {
      id: "supply-fengbin",
      name: "Fengbin resupply",
      kind: "supply",
      lat: 23.598,
      lng: 121.521,
      note: "Top up water and food before the sparse coast south.",
      verified: false,
      sourceIds: ["walker-east-coast", "east-coast-depots"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=7-Eleven+Fengbin+Taiwan",
    },
    {
      id: "caution-suhua",
      name: "Suhua road check",
      kind: "caution",
      lat: 24.35,
      lng: 121.76,
      note: "Confirm tunnel access, closures, and traffic conditions before riding.",
      verified: true,
      sourceIds: ["road-conditions", "david-sykes"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Suhua+Highway+Taiwan",
    },
    {
      id: "caution-wuling",
      name: "Wuling alpine decision",
      kind: "caution",
      lat: 24.137,
      lng: 121.276,
      note: "3,275 m pass: weather, lodging, acclimatisation, and road status are mandatory checks.",
      verified: true,
      sourceIds: ["road-conditions", "david-sykes", "bike-express-wuling"],
      mapsUrl: "https://www.google.com/maps/search/?api=1&query=Wuling+Pass+Taiwan",
    },
  ],
};
